-- 코드를 입력하세요
SELECT CAR_ID, C.CAR_TYPE, (DAILY_FEE * 30) * (100 - DISCOUNT_RATE) / 100 FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(END_DATE, 'YYYY-MM-DD') > '2022-11-01'
)
AND C.CAR_TYPE IN ('세단', 'SUV')
AND (DAILY_FEE * 30) * (100 - DISCOUNT_RATE) / 100 >= 500000
AND (DAILY_FEE * 30) * (100 - DISCOUNT_RATE) / 100 < 2000000
ORDER BY 3 DESC, 2, 1 DESC