-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME,
       (CITY||' '||STREET_ADDRESS1||' '||STREET_ADDRESS2) "전체주소", 
       SUBSTR(U.tlno, 0, 3)||'-'||SUBSTR(U.tlno, 4, 4)||'-'||SUBSTR(U.tlno, 8, 9) "전화번호"
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID, U.NICKNAME, (CITY||' '||STREET_ADDRESS1||' '||STREET_ADDRESS2), U.tlno
HAVING COUNT(B.WRITER_ID) >= 3
ORDER BY U.USER_ID DESC