-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT USER_ID) AS USERS
FROM (SELECT TO_CHAR(SALES_DATE,'YYYY') AS YEAR,
             TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS MONTH, 
             GENDER, 
             U.USER_ID 
      FROM USER_INFO U JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID 
      WHERE GENDER IS NOT NULL)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER