-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID, U.NICKNAME, STATUS
HAVING SUM(B.PRICE) >= 700000 AND STATUS LIKE 'DONE'
ORDER BY SUM(B.PRICE)