-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY, TO_CHAR(S.SALES_DATE, 'YYYY-MM')
HAVING TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
ORDER BY CATEGORY ASC