-- 코드를 입력하세요
SELECT FLAVOR
FROM (
      SELECT F.FLAVOR, SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL_ORDER
      FROM FIRST_HALF F LEFT JOIN JULY J
      ON F.FLAVOR = J.FLAVOR
      GROUP BY F.FLAVOR
      ORDER BY SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
    )
WHERE ROWNUM <= 3