-- 코드를 입력하세요
SELECT T.FLAVOR
FROM (
    SELECT F.SHIPMENT_ID, F.FLAVOR, SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF F JOIN JULY J
    ON F.FLAVOR = J.FLAVOR
    GROUP BY F.SHIPMENT_ID, F.FLAVOR
    ORDER BY TOTAL DESC
) T
LIMIT 3