-- 코드를 입력하세요
SELECT A.HOUR, COUNT(B.TIME) COUNT
FROM (SELECT LEVEL-1 HOUR FROM DUAL CONNECT BY LEVEL <25) A
LEFT JOIN (SELECT TO_CHAR(DATETIME, 'HH24') TIME FROM ANIMAL_OUTS) B 
ON A.HOUR = B.TIME
GROUP BY A.HOUR
ORDER BY A.HOUR